### ISSUE TITLE
Please use a consistent name for your project.

### ISSUE THREAD

**Issue by Claycorp** [Lebeg134/TFC-PH_Compat#1]
Currently there's 4 names: "tpc", "TFC-PH_compatibility", "TFC_PH_Compat" and "TFC-Pam's harvestcraft compatibility mod".

The mod ID should match the name of the project. Don't use acronyms.
Your CF project, Github name and jar name should be similar as if an issue comes up it's easily searched.

You should also think about adding dependency information to the mod itself. [https://mcforge.readthedocs.io/en/1.12.x/gettingstarted/structuring/](https://mcforge.readthedocs.io/en/1.12.x/gettingstarted/structuring/)

**Comment by Lebeg134** [comment]
I've changed the mod ID and made the naming more consistent. I also included the dependencies in the mod itself. Thanks for the feedback.
