### ISSUE TITLE
Crash | Duplicate Capability Key

### ISSUE THREAD

**Issue by drhaber** [Lebeg134/TFC-PH_Compat#2]
After loading this mod into my pack I get a crash with the following error 

`Duplicate Capability Key: tfc:item_heat net.dries007.tfc.api.capability.food.FoodHeatHandler@34d38b1c`

please see attached files for crash report and mod list sorted by author 

[crash-2021-03-15_12.13.34-client.txt](https://github.com/Lebeg134/TFC-PH_Compat/files/6142901/crash-2021-03-15_12.13.34-client.txt)

[authors.txt](https://github.com/Lebeg134/TFC-PH_Compat/files/6142916/authors.txt)

**Comment by Lebeg134** [comment]
This bug will be fixed in the next update.
Also you might want to check for conflicting heating recipes in your modpack (like heating tfc potatos and stuff)
