### ISSUE TITLE
[bug] Mod doesn't get recognised sometimes

### ISSUE THREAD

**Issue by Lebeg134** [Lebeg134/TFC-PH_Compat#4]
Sometimes when the mod is added it doesn't get recognised and won't load.

**Comment by drhaber** [comment]
So I loaded the release version from Curse and the mod did load successfully! 
Nutrition too! 
<img width="537" alt="Screen Shot 2021-04-01 at 1 27 38 PM" src="https://user-images.githubusercontent.com/56454522/113331494-09401b00-92ee-11eb-8184-a77f75787b61.png">

Edit: Testing Primary pack now: It works here too!

**Comment by Lebeg134** [comment]
Nice maybe it was just a bug with the dev build
